# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # - name: run node
  #   before: cd nodeWebSocket
  #   init: npm i
  #   command: node main.js
  - name: run docker node
    command: docker-compose up -d
  # - name: run mysql server
  #   before: cd WS && docker-compose up -d
  #   init: docker exec -i mysql sh -c 'exec mysql -ucyber -pAdminDB02' < cyberbullism.sql
  # - name: install php mysql
  #   init: sudo apt install php-mysql -y

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: websocket
    port: 8080
    visibility: public
