version: '3'
services:
  nodeWS:
    image: node_web_socket
    build: ./nodeWebSocket
    ports:
      - "8080:8080"
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: cyber
      MYSQL_PASSWORD: AdminDB02
      MYSQL_DATABASE: cyberbullism
    volumes:
      - ./SQL/mySqlData/:/var/lib/mysql