version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: cyber
      MYSQL_PASSWORD: AdminDB02
      MYSQL_DATABASE: cyberbullism